### ISSUE TITLE
Jekyll --> GatsbyJS

### ISSUE THREAD

**Issue by luserx0** [luserx0/Blog#18]
Port blog to Gatsby JS and use the Casper Blog theme as a starter

**Comment by An0u** [comment]
Error: Unable to find plugin "gatsby-transformer-json". Perhaps you need to install its package?
  When trying to 'Gatsby build/develop'

**Comment by An0u** [comment]
Port has beel completed. We are now at the stage of advising how the Casper theme will be customized for proper usage.
