### ISSUE TITLE
Sanity Dependencies for Gatsby JS

### ISSUE THREAD

**Issue by An0u** [luserx0/Blog#19]

**Comment by luserx0** [comment]
How are the Sanity dependencies gonna be satisfied? Is it just an ```npm install sanity``` command or is there something more needed?

Could you provide a short description?

**Comment by An0u** [comment]
https://www.sanity.io/blog/how-to-quickly-set-up-a-gatsby-js-jamstack-website-with-a-headless-cms

**Install the Sanity CLI**
npm install --global @sanity/cli
**Install dependencies:**
~/example-company-website-gatsby-sanity-combo
npm install
**Set up Sanity.io as a headless CMS:**
~/example-company-website-gatsby-sanity-combo
npm run init
