### ISSUE TITLE
Blog Name

### ISSUE THREAD

**Issue by An0u** [luserx0/Blog#21]
Co-decide on the blog new name and identity

**Comment by luserx0** [comment]
**Also on Site's:**
* Description
* Credits
* About 
Sections

**Comment by An0u** [comment]
Name: 
**1. Pessimistic Insights
2. Esoteric Insights
3. Hacker's Paradigm**

**Description/Credits:** Can these be merged into one? 

About Sections:  
**1. Bio
2. Contact
3. About the Blog
4. Copyright**
© Luserx0, 2019.
Unauthorized use and/or duplication of this material without express and written permission from this site’s author and/or owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to Luserx0 with appropriate and specific direction to the original content. 

**5. Topics**

**Comment by luserx0** [comment]
Name:
- **Opinionated Bits** -- if it's not taken
  - orelse, Pessimistic Paradigms sounds kewl

Sections:
-- No Bio
-- Contact will be available iether to the left or the bottom or in the credits section
-- About the Blog what? No section like this
-- Copyright (as always) goes to the footer as a link to the blog.luserx0.cc/credits site path

**Comment by An0u** [comment]
Name:

- Opinionated Bits & Bobs -- couldn't resist

- Opinionated Bits -- sounds good

**Comment by luserx0** [comment]
Latest; persists
