### ISSUE TITLE
CMS Integration

### ISSUE THREAD

**Issue by luserx0** [luserx0/Blog#22]
### Incorporate a Content Management System to our current Blog structure.

- Potential CMSs:
* sanity.io
* contentful

**Comment by luserx0** [comment]
Please track with your current progress and findings this issue

**Comment by An0u** [comment]
**Other potential candidate CMSs:**

- strapi
I like the Interface of this one a lot more.
https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/

1. Previous tries of implementing it directly to the source code failed. Making it simpler to understand what's going on.
2. Currently at the step of creating a dummy site to check strapi-gatsby integration.

**Comment by luserx0** [comment]
Hexo saved my eyes
